const pokemons = [
  {
    name: "Bulbasaur",
    height: "0,7m",
    weight: "6,9kg",
    hp: "45",
    atk: "49",
    def: "49",
    spd: "45",
    satk: "65",
    sdef: "65",
    moves: "overgrow,chlorophyll",
    move1: "overgrow",
    moves2: "chlorophyll",
    type1: "Grass",
    type2: "Poison",
    type1color: "#74CB48",
    type2color: "#A43E9E",
    number: "#001",
    color: "#74CB48",
    description:
      "There isaplant seed on its back right from the day this Pokémon is born.The seed slowly grows larger",
  },

  {
    name: "Charmander",
    height: "0,6m",
    weight: "8,5kg",
    hp: "39",
    atk: "52",
    def: "43",
    spd: "65",
    satk: "60",
    sdef: "50",
    moves: "blaze,solar-power",
    move1: "blaze",
    moves2: "power",

    type1: "Fire",
    type2: "",
    number: "#004",
    color: "#F57D31",
    type1color: "#F57D31",
    type2color: "",
    description:
      "The flame on its tail shows the strength of its life force. If it is weak, the flame also burns weakly",
  },

  {
    name: "Squirtle",
    height: "0,5m",
    weight: "9,0kg",
    hp: "44",
    atk: "48",
    def: "65",
    spd: "43",
    satk: "50",
    sdef: "64",
    moves: "torrent,rain-dish",
    type1: "Water",
    type2: "",
    number: "#007",
    color: "#6493EB",
    type1color: "#6493EB",
    type2color: "",
    description:
      "Shoots water at prey while in the water. Withdraws into its shell when in danger",
  },
  {
    name: "ButterFree",
    height: "11m",
    weight: "3,20kg",
    hp: "60",
    atk: "45",
    def: "50",
    spd: "70",
    satk: "90",
    sdef: "80",
    moves: "compound-eyes,tinted-lens",
    move1: "compound-eyes",
    move2: "tinted-lens",
    type1: "Bug",
    type2: "Flying",
    number: "#012",
    color: "#A7B723",
    type1color: "#A7B723",
    type2color: "#A891EC",
    description:
      "In battle, it flaps its wings at high speed to release highly toxic dust into the air",
  },
  {
    name: "Pikachu",
    height: "0.4m",
    weight: "6,0kg",
    hp: "35",
    atk: "55",
    def: "40",
    spd: "90",
    satk: "50",
    sdef: "50",
    moves: "static,lightning-rod",
    move1: "static",
    move2: "lightning-rod",
    type1: "Electric",
    type2: "",
    number: "#025",
    color: "#F9CF30",
    type1color: "#F9CF30",
    type2color: "",
    description:
      "It keeps its tail raised to monitor its surroundings. If you yank its tail, it will try to bite you",
  },
  {
    name: "Gastly",
    height: "1.3m",
    weight: "1kg",
    hp: "30",
    atk: "35",
    def: "30",
    spd: "80",
    satk: "100",
    sdef: "35",
    moves: "levitate",
    move1: "static",
    move2: "",
    type1: "Ghost",
    type2: "Poison",
    color: "#70559B",
    type1color: "#70559B",
    type2color: "#A43E9E",
    description:
      "Almost invisible, this gaseous POKéMON cloaks the target and puts it to sleep without notice.",
    number: "#082",
  },
  {
    name: "Ditto",
    height: "0.3m",
    weight: "40kg",
    hp: "48",
    atk: "48",
    def: "48",
    spd: "48",
    satk: "48",
    sdef: "48",
    moves: "limber,imposter",
    move1: "limber",
    move2: "imposter",
    type1: "Normal",
    type2: "",
    color: "#AAA67F",
    type1color: "#AAA67F",
    type2color: "",
    description:
      "Capable of copying an enemy's genetic code to instantly transform itself into a duplicate of the enemy.",
    number: "#132",
  },
  {
    name: "Mew",
    height: "0.4m",
    weight: "40kg",
    hp: "100",
    atk: "100",
    def: "100",
    spd: "100",
    satk: "100",
    sdef: "100",
    move1: "synchronize",
    move2: "",
    type1: "Psychic",
    type2: "",
    color: "#FB5584",
    type1color: "#FB5584",
    type2color: "",
    description:
      "So rare that it is still said to be a mirage by many experts. Only a few people have seen it worldwide.",
    number: "#182",
  },
  {
    name: "Aron",
    height: "0.4m",
    weight: "600kg",
    hp: "50",
    atk: "70",
    def: "100",
    spd: "30",
    satk: "40",
    sdef: "40",
    moves: "rock-head heavy-metal",
    move1: "synchronize",
    move2: "",
    type1: "Steel",
    type2: "Rock",
    color: "#B789D0",
    type1color: "#B789D0",
    type2color: "#B69E31",
    description:
      "This POKéMON has a body of steel. To make its body, ARON feeds on iron ore that it digs from mountains. Occasionally, it causes major trouble by eating bridges and rails.",
    number: "#304",
  },
];
export default pokemons;
